image: docker:latest
services:
    - docker:dind

variables:
    DOCKER_DRIVER: overlay

stages:
    - build
    - deploy

variables:
    BRANCH: "develop"
    TAG: "develop"

ubuntu-image:
    stage: build
    script:
        - docker build --build-arg "OPENRCT2_REF=$BRANCH" -t "corysanin/openrct2-cli:$TAG-ubuntu" -f ./develop/cli-ubuntu/Dockerfile .
        - "if [ ! -z ${DOCKER_PASSWORD+x} ]; then echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin; docker push \"corysanin/openrct2-cli:$TAG-ubuntu\"; fi"

debian-image:
    stage: build
    script:
        - docker build --build-arg "OPENRCT2_REF=$BRANCH" -t "corysanin/openrct2-cli:$TAG-debian" -t "corysanin/openrct2-cli:$TAG" -f ./develop/cli-debian/Dockerfile .
        - "if [ ! -z ${DOCKER_PASSWORD+x} ]; then echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin; docker push \"corysanin/openrct2-cli:$TAG-debian\"; docker push \"corysanin/openrct2-cli:$TAG\"; fi"

alpine-image:
    stage: build
    script:
        - docker build --build-arg "OPENRCT2_REF=$BRANCH" -t "corysanin/openrct2-cli:$TAG-alpine" -f ./develop/cli-alpine/Dockerfile .
        - "if [ ! -z ${DOCKER_PASSWORD+x} ]; then echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin; docker push \"corysanin/openrct2-cli:$TAG-alpine\"; fi"

# this step exists to trigger the deploy webhook
deploy:
    stage: deploy
    script:
        - "echo 'images successfully pushed to corysanin/openrct2-cli'"