image: jonoh/docker-buildx-qemu:latest
services:
    - docker:dind

variables:
    DOCKER_DRIVER: overlay

stages:
    - build

variables:
    BRANCH: "develop"
    TAG: "develop"

alpine-image:
    stage: build
    before_script:
        - docker buildx create --use
    script:
       - docker buildx build --build-arg "OPENRCT2_REF=$BRANCH" -t "corysanin/openrct2-test:$TAG-alpine" -f ./develop/cli-alpine/Dockerfile .
        - "if [ "test" ]; then echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin; docker buildx build --push --build-arg \"OPENRCT2_REF=$BRANCH\" -t \"corysanin/openrct2-test:$TAG-alpine\" -f ./develop/cli-alpine/Dockerfile .; fi"
